#!/usr/bin/env python3
"""Rebuild index.md from all entry files."""
import os, yaml
from collections import defaultdict


def rebuild_index(entries_dir: str, index_path: str) -> tuple:
    if not os.path.isdir(entries_dir):
        print(f'Error: entries directory not found: {entries_dir}')
        return (0, 0, 0)
    
    by_month = defaultdict(list)
    bad = []
    total = 0
    
    for fname in sorted(os.listdir(entries_dir)):
        if not fname.endswith('.md'):
            continue
        total += 1
        path = os.path.join(entries_dir, fname)
        
        with open(path) as f:
            content = f.read()
        
        if not content.startswith('---\n'):
            bad.append((fname, 'Missing YAML frontmatter'))
            continue
        
        parts = content.split('---\n', 2)
        if len(parts) < 3:
            bad.append((fname, 'Incomplete frontmatter'))
            continue
        
        try:
            meta = yaml.safe_load(parts[1])
        except yaml.YAMLError:
            bad.append((fname, 'Invalid YAML'))
            continue
        
        if not isinstance(meta, dict):
            bad.append((fname, 'Frontmatter not a mapping'))
            continue
        
        date = str(meta.get('date', 'unknown'))
        agent = str(meta.get('agent', 'unknown'))
        topic = str(meta.get('topic', 'unknown'))
        confidence = str(meta.get('confidence', 'unknown'))
        
        month_key = date[:7] if len(date) >= 7 else 'unknown'
        by_month[month_key].append({
            'date': date, 'agent': agent, 'topic': topic,
            'confidence': confidence, 'file': fname,
            'path': f'entries/{fname}'
        })
    
    lines = []
    lines.append('# Collective Memory Index')
    lines.append('_Auto-generated by collective-memory-curator reindex.py_')
    lines.append('')
    
    indexed = 0
    for month in sorted(by_month.keys(), reverse=True):
        entries = by_month[month]
        lines.append(f'---\n')
        lines.append(f'## {month}\n')
        lines.append('| Date | Agent | Topic | Confidence | Entry |')
        lines.append('|------|-------|-------|------------|-------|')
        for e in entries:
            indexed += 1
            link = f'[{e["file"]}]({e["path"]})'
            lines.append(f'| {e["date"]} | {e["agent"]} | {e["topic"]} | {e["confidence"]} | {link} |')
        lines.append('')
    
    lines.append('---')
    lines.append(f'**Total: {indexed} entries, {len(bad)} malformed**')
    
    with open(index_path, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    
    return (total, indexed, len(bad))


if __name__ == '__main__':
    base = os.path.join(os.path.dirname(__file__), '..', '..', '..', 'collective-memory')
    entries_dir = os.path.join(base, 'entries')
    index_path = os.path.join(base, 'index.md')
    
    total, indexed, bad = rebuild_index(entries_dir, index_path)
    print(f'Entries scanned: {total}')
    print(f'Entries indexed: {indexed}')
    print(f'Malformed: {bad}')
    if bad:
        print(f'\n⚠️ {bad} entries need manual review')
    print('\nindex.md rebuilt.')